/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/flower/FLowers_1.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Flowers(props) {
  const { nodes, materials } = useGLTF("/models/flower/Flowers_1.gltf");
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed">
        <mesh
          castShadow
          geometry={nodes.Cube432.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube432_1.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          castShadow
          geometry={nodes.Cube432_2.geometry}
          material={materials.Atlas}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/models/flower/Flowers_1.gltf");
